apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec: 
      containers:
        # Это название важно только для процесса логирования
        - name: auth 
          image: jgslahrb/blog-auth
          # Тут нужно чтобы была выполнена команда для создания ключа заранее
          # Вот эта: kubectl create secret generic jwt-secret --from-literal=JWT_KEY=asdf
          # Иначе kubectl не будет нахдить ключ с именем - jwt-secret
          env: 
            - name: JWT_KEY
              valueFrom: 
                secretKeyRef:
                  # Если мыменяе имя то нужно создать секретный ключ с таким же именем
                  # kubectl create secret generic jwt-secret --from-literal=JWT_KEY=asdf
                  name: jwt-secret
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec: 
  selector: 
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000